// <auto-generated />
namespace ChatAppTest1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class privatechat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(privatechat));
        
        string IMigrationMetadata.Id
        {
            get { return "201912311036035_private chat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
