// <auto-generated />
namespace ChatAppTest1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TestGit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestGit));
        
        string IMigrationMetadata.Id
        {
            get { return "202001091455207_Test Git"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
